### ISSUE TITLE
logo issue

### ISSUE THREAD

**Issue by pradipbhatt** [pradipbhatt/iCEC-Page#14]
![Screenshot from 2024-10-16 16-29-02](https://github.com/user-attachments/assets/b3670ead-b928-4421-8a7e-3a35f50b47ad)

**Comment by UmerMehmood1** [comment]
Already Solved

**Comment by pradipbhatt** [comment]
> Already Solved

Thank you for verifying !

**Comment by pradipbhatt** [comment]
solved
