### ISSUE TITLE
Add Hover Effect to Navbar Links

### ISSUE THREAD

**Issue by Manikant69** [pradipbhatt/iCEC-Page#16]
The **Navbar links** currently lack a hover effect, which reduces interactivity and visual feedback for users navigating the website. Adding a subtle hover effect to these links will enhance the user experience, making the navigation feel more responsive and engaging.

#### Expected Behavior:
- The navbar links should have a hover effect (such as a color change, underline, or text shadow) to indicate that they are clickable.

![WhatsApp Image 2024-10-16 at 17 38 42_adb9ade1](https://github.com/user-attachments/assets/42428bd7-2bb7-4fc3-9e04-19bfde1ab439)

**Comment by Manikant69** [comment]
hey Pradip, assign me this so i can fix this issue.

**Comment by SartHak-0-Sach** [comment]
Hi @pradipbhatt, I would love to work on this issue, please assign me this and allow me to contribute to it

**Comment by pradipbhatt** [comment]
> Hi @pradipbhatt, I would love to work on this issue, please assign me this and allow me to contribute to it

ok sure @SartHak-0-Sach go on !

**Comment by Manikant69** [comment]
this is not fair @pradipbhatt, i raised the issue but you how can assign to @SartHak-0-Sach .

**Comment by pradipbhatt** [comment]
> this is not fair @pradipbhatt, i raised the issue but you how can assign to @SartHak-0-Sach .

make PR i'll accept your PR as well,
Happy coding

**Comment by SartHak-0-Sach** [comment]
> > Hi @pradipbhatt, I would love to work on this issue, please assign me this and allow me to contribute to it
> 
> ok sure @SartHak-0-Sach go on !

Sweet, thanks a lot😇

**Comment by umeshbhatt2057** [comment]
@Manikant69 @SartHak-0-Sach  Are you guys working on this ???
