### ISSUE TITLE
Next bottons layout  < >

### ISSUE THREAD

**Issue by pradipbhatt** [pradipbhatt/iCEC-Page#20]
![image](https://github.com/user-attachments/assets/a26c09cc-2a67-411c-acd6-994597308755)
Enhance this slider

**Comment by Suvendu-UI** [comment]
pls assign me this issue ?

**Comment by pradipbhatt** [comment]
> pls assign me this issue ?

ok @Suvendu-UI  try this !

**Comment by umeshbhatt2057** [comment]
This is fixed

**Comment by pradipbhatt** [comment]
> This is fixed

nice but can you make much better than this

**Comment by pradipbhatt** [comment]
![image](https://github.com/user-attachments/assets/160305a5-ee98-4708-9601-0963db011830)
### **Solved thank you @umeshbhatt2057 **
