### ISSUE TITLE
Enhance this onhover and add aniamtions 

### ISSUE THREAD

**Issue by pradipbhatt** [pradipbhatt/iCEC-Page#27]
![image](https://github.com/user-attachments/assets/5434c034-f494-498d-aff8-ee16166c0296)
### **Add on hover effects and animations as well**
**you may try your design and layout as well best one gonna merged**

**Comment by kiran1901** [comment]
Hi @pradipbhatt , I would like to work on this issue, Could you please assign this to me?

**Comment by pradipbhatt** [comment]
> Hi @pradipbhatt , I would like to work on this issue, Could you please assign this to me?

ok do it and send PR

**Comment by arbazahmed07** [comment]
hey can you please assign me this @pradipbhatt

**Comment by pradipbhatt** [comment]
> hey can you please assign me this @pradipbhatt

@arbazahmed07 ok you may try and send PR i'll check if it's ok then i'll accept !

**Comment by pradipbhatt** [comment]
> > > hey can you please assign me this @pradipbhatt
> > 
> > 
> > @arbazahmed07 ok you may try and send PR i'll check if it's ok then i'll accept !
> 
> hey @pradipbhatt I made the PR can you check it once

Merged well done
