### ISSUE TITLE
Dropdown Menu Visibility on Navbar Links

### ISSUE THREAD

**Issue by umeshbhatt2057** [pradipbhatt/iCEC-Page#39]
![image](https://github.com/user-attachments/assets/48943e59-eec7-4c36-952a-438c970551fb)
The dropdown menus for various sections in the navbar (e.g., "Our Team," "Publications") currently become visible when hovering over the entire area of their respective parent <div> elements. This behavior can lead to unintended dropdown visibility, as it activates even when hovering outside the specific buttons.

1. **Current Behavior:**

Dropdown menus appear when hovering over the entire area of each navbar section, including any space around the buttons.

2. **Desired Behavior:**

Dropdown menus should only become visible when the user hovers directly over the respective navbar buttons. This will enhance usability by preventing accidental dropdowns.

**Comment by Abhineetsahay** [comment]
i am doing it

**Comment by saadii00** [comment]
Can you please elaborate as far as i have seen the navbar buttons are working fine and already according to the desired output.

**Comment by lakshita10341** [comment]
i would like to work on this issue. can u please assign it to me

**Comment by pradipbhatt** [comment]
> Can you please elaborate as far as i have seen the navbar buttons are working fine and already according to the desired output.

@saadii00 you may make like while hover the navlinks make a underline appers from center to left-right insmooth transition for better user navigation experience

**Comment by pradipbhatt** [comment]
> i would like to work on this issue. can u please assign it to me

@lakshita10341 you may try as well and give PR

**Comment by lakshita10341** [comment]
#45
I have fixed the issue and raised the PR. Kindly check it.

**Comment by pradipbhatt** [comment]
> #45 I have fixed the issue and raised the PR. Kindly check it.

### **It's already been fixed can you work on other issues !**

**Comment by lakshita10341** [comment]
okayy sure
