### ISSUE TITLE
Enhance the footer layout

### ISSUE THREAD

**Issue by pradipbhatt** [pradipbhatt/iCEC-Page#4]
![Screenshot from 2024-10-16 11-54-14](https://github.com/user-attachments/assets/7045032a-6704-42ae-ae33-99664ccb02e1)

**Comment by Abhineetsahay** [comment]
can i take this issue

**Comment by pradipbhatt** [comment]
> can i take this issue

yes,sure you may

**Comment by Abhineetsahay** [comment]
![image](https://github.com/user-attachments/assets/dc5bc663-40f8-435c-bfe3-3754578b9354)
should i improve it more

**Comment by pradipbhatt** [comment]
> ![image](https://private-user-images.githubusercontent.com/145606273/376939134-dc5bc663-40f8-435c-bfe3-3754578b9354.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNjQzNDMsIm5iZiI6MTcyOTA2NDA0MywicGF0aCI6Ii8xNDU2MDYyNzMvMzc2OTM5MTM0LWRjNWJjNjYzLTQwZjgtNDM1Yy1iZmUzLTM3NTQ1NzhiOTM1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwNzM0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGQ5MGJiMzFmZTc4ZjQxM2NhOWJmOGU5YWFhNDVkYTFjNjY1ODdkOTNlNTYwMGY4ODRmNmI3N2Y4YzkyNzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iyuNPqDPwtGoPWdRMuhRnDAI7UL99oZv0AIxFI8Ln4k) should i improve it more

you may push into develop branch and give me PR

**Comment by Abhineetsahay** [comment]
can you check my PR?

**Comment by pradipbhatt** [comment]
> can you check my PR?

Well done it's merged you may solve other issues as well 🥳
#hacktoberfest
