### ISSUE TITLE
responsive issue

### ISSUE THREAD

**Issue by pradipbhatt** [pradipbhatt/iCEC-Page#5]
![Screenshot from 2024-10-16 13-10-52](https://github.com/user-attachments/assets/8a4dd225-c6c8-4a59-82a8-f16bc726bc61)

**Comment by pradipbhatt** [comment]
Anyone may try to solve this issue in sm: devices

**Comment by Anuraj-IND** [comment]
lemme try to handle this issue assign me this

**Comment by pradipbhatt** [comment]
> lemme try to handle this issue assign me this

ok @Anuraj-IND do it

**Comment by Anuraj-IND** [comment]
assign me this 
ill fork it and start working on it

**Comment by pradipbhatt** [comment]
> assign me this ill fork it and start working on it

you may fork and work on it @Anuraj-IND

**Comment by Anuraj-IND** [comment]
um sir havent you shared whole code ? i tried to open index.html with live server and it was just a blank web page

**Comment by pradipbhatt** [comment]
> um sir havent you shared whole code ? i tried to open index.html with live server and it was just a blank web page

it's react project basically you need to install node modules by npm install then run by using npm run dev

**Comment by Anuraj-IND** [comment]
im really sorry but im a django dev and yea i fired npm run dev to run ur web app and its working but to make it responsive i need time to understand your code thing is im short of time sadly i have sessionals exams so i cant put all time in it man its so interesting btw if theres any way to use bootstrap in it just use it copy paste links of bootstraps and capsulate things in <div class="container"> </container> then you just have to fine tune it itll not take much time im sorry really wanted to work on it but i dont have time rn to explore react

**Comment by pradipbhatt** [comment]
> im really sorry but im a django dev and yea i fired npm run dev to run ur web app and its working but to make it responsive i need time to understand your code thing is im short of time sadly i have sessionals exams so i cant put all time in it man its so interesting btw if theres any way to use bootstrap in it just use it copy paste links of bootstraps and capsulate things in
> 
> then you just have to fine tune it itll not take much time im sorry really wanted to work on it but i dont have time rn to explore react

no worries @Anuraj-IND thank you ,
we really appreciate your enthuisim on Open source contributions !
Keep going and best of luck for your exams !
